version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/app/" # Location of package manifests
    schedule:
      interval: "weekly"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"