version: "3"

services:
  do-dyndns:
    image: hellstromitltd/do-dyndns:v0.1.2
    container_name: do-dynds
    environment:
      - DO_TOKEN=<your digitalocean token>
    volumes:
      - ./config.yml:/data/config.yml:ro
    restart: unless-stopped
