{{- if not .Values.digitalocean.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "do-dyndns.fullname" . }}
  labels:
    {{- include "do-dyndns.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "digitalocean.token or digitalocean.existingSecret must be set" .Values.digitalocean.token | b64enc | quote }}
{{- end }}
